steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-central1-docker.pkg.dev/sfujiwara/docker/sfujiwara', '.']

- name: gcr.io/cloud-builders/docker
  args: ['push', 'us-central1-docker.pkg.dev/sfujiwara/docker/sfujiwara']

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: ['run', 'deploy', 'sfujiwara', '--image', 'us-central1-docker.pkg.dev/sfujiwara/docker/sfujiwara', '--region', 'us-central1']

images:
  - us-central1-docker.pkg.dev/sfujiwara/docker/sfujiwara
